version: "3"
services:
  qa-exercices-php:
    container_name: qa-exercices-php
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    restart: unless-stopped
    environment:
      - PUID=1000
      - GUID=1000
      - TZ=Europe/Paris
      - HOST=0.0.0.0
    ports:
      - '8888:8000'
    volumes:
      - ./:/home/qa-exercices-php:cached